# Generated by Django 2.1.4 on 2019-01-31 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stuff', '0012_auto_20190131_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of tracked time')),
                ('tracked_time', models.TimeField(verbose_name="Person's tracking time")),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.Person', verbose_name='Person')),
            ],
        ),
    ]
