# Generated by Django 2.1.4 on 2018-12-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company name')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=150, verbose_name='Door title')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='door_to_company', to='company.Company', verbose_name='Door to company')),
            ],
        ),
    ]
