# Generated by Django 2.1.4 on 2018-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_auto_20181220_1509'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='allowed_person',
            field=models.ManyToManyField(to='stuff.Person'),
        ),
    ]
