# Generated by Django 2.1.4 on 2018-12-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_door_allowed_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='allowed_person',
            field=models.ManyToManyField(blank=True, to='stuff.Person'),
        ),
    ]
