# Generated by Django 2.1.4 on 2018-12-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20181221_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Start'), (2, 'Stop'), (3, 'Nothing')], default=3, verbose_name='Status'),
        ),
    ]
