# Generated by Django 2.1.4 on 2019-01-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190116_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='door_name',
            new_name='name',
        ),
    ]
