# Generated by Django 2.1.4 on 2019-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190117_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Start tracking'), (2, 'Stop tracking'), (3, 'Nothing')], default=3, verbose_name='Status'),
        ),
    ]
