# Generated by Django 2.1.4 on 2019-01-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_door_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company'),
        ),
    ]
