# Generated by Django 2.1.4 on 2019-02-04 15:39

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20190117_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London', verbose_name='Company timezone'),
        ),
        migrations.AlterField(
            model_name='door',
            name='allowed_person',
            field=models.ManyToManyField(blank=True, to='stuff.Person', verbose_name='People who are allowed'),
        ),
    ]
