# Generated by Django 2.1.4 on 2019-02-09 15:56

import company.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_current_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timezone',
            field=company.fields.AdvancedTimeZoneField(default='Europe/London', verbose_name='Company timezone'),
        ),
    ]
