# Generated by Django 2.1.4 on 2018-12-19 14:40

from django.db import migrations, models
import face_recognizer_server.utils.upload_location


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=face_recognizer_server.utils.upload_location.upload_temp_photo_of_person)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
