# Generated by Django 2.1.4 on 2018-12-20 10:08

from django.db import migrations, models
import django.db.models.deletion
import face_recognizer_server.utils.upload_location


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('stuff', '0002_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personphoto',
            old_name='to_user',
            new_name='to_person',
        ),
        migrations.RemoveField(
            model_name='file',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='person',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_to_company', to='company.Company', verbose_name='To company'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='photo',
            field=models.ImageField(upload_to=face_recognizer_server.utils.upload_location.upload_photo_of_person, verbose_name='Photo'),
        ),
    ]
