# Generated by Django 2.1.4 on 2018-12-20 15:09

from django.db import migrations, models
import django.db.models.deletion
import face_recognizer_server.utils.upload_location


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('stuff', '0003_auto_20181220_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEntryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=face_recognizer_server.utils.upload_location.upload_temp_photo_of_person)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='door', to='company.Door', verbose_name='Used door')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
