# Generated by Django 2.1.4 on 2019-01-16 17:20

from django.db import migrations, models
import django.db.models.deletion
import face_recognizer_server.utils.upload_location


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190116_1720'),
        ('stuff', '0004_auto_20181220_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcretePersonActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Start tracking'), (2, 'Stop tracking'), (3, 'Nothing')], default=3, verbose_name='Status')),
                ('file', models.FileField(upload_to=face_recognizer_server.utils.upload_location.upload_temp_photo_of_person)),
            ],
        ),
        migrations.CreateModel(
            name='PersonVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_video_file', models.FileField(upload_to=face_recognizer_server.utils.upload_location.upload_video_of_person)),
            ],
        ),
        migrations.RemoveField(
            model_name='personentrylog',
            name='door',
        ),
        migrations.RemoveField(
            model_name='person',
            name='to_company',
        ),
        migrations.RemoveField(
            model_name='personphoto',
            name='to_person',
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company', verbose_name='Company FK'),
        ),
        migrations.AddField(
            model_name='personphoto',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Person', verbose_name='Person FK'),
        ),
        migrations.DeleteModel(
            name='PersonEntryLog',
        ),
        migrations.AddField(
            model_name='personvideo',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Person', verbose_name='Person FK'),
        ),
        migrations.AddField(
            model_name='concretepersonactionhistory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.Person', verbose_name='Person FK'),
        ),
    ]
