# Generated by Django 2.1.4 on 2019-01-17 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190117_0915'),
        ('stuff', '0005_auto_20190116_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretepersonactionhistory',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Door', verbose_name='Door FK'),
        ),
    ]
