# Generated by Django 2.1.4 on 2019-01-17 12:09

from django.db import migrations, models
import face_recognizer_server.utils.upload_location


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_concretepersonactionhistory_door'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretepersonactionhistory',
            name='file',
            field=models.ImageField(upload_to=face_recognizer_server.utils.upload_location.upload_temp_photo_of_person),
        ),
    ]
