# Generated by Django 2.1.4 on 2019-01-17 17:29

from django.db import migrations, models
import django.db.models.deletion
import face_recognizer_server.utils.upload_location


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0007_auto_20190117_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='concretepersonactionhistory',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Door', verbose_name='Door'),
        ),
        migrations.AlterField(
            model_name='concretepersonactionhistory',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=face_recognizer_server.utils.upload_location.upload_temp_photo_of_person),
        ),
        migrations.AlterField(
            model_name='concretepersonactionhistory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='personphoto',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='personvideo',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stuff.Person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='persontracking',
            name='action_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.ConcretePersonActionHistory', verbose_name='Action history'),
        ),
    ]
