# Generated by Django 2.1.4 on 2019-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_auto_20190117_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='personphoto',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Is this photo new'),
        ),
        migrations.AddField(
            model_name='personvideo',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Is this video new'),
        ),
    ]
