# Generated by Django 2.1.4 on 2019-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_auto_20190123_1147'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concretepersonactionhistory',
            index=models.Index(fields=['-timestamp'], name='stuff_concr_timesta_02e766_idx'),
        ),
    ]
