# Generated by Django 2.1.4 on 2019-02-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0014_auto_20190216_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is this person active'),
        ),
    ]
